### ISSUE TITLE
Fix analysis funcs so they work with NetStim (as stim not pops)

### ISSUE THREAD

**Issue by salvadord** [suny-downstate-medical-center/netpyne#207]
- previously changed internal implementation of NetStims but didn't update some analysis funcs
- already fixed plotRaster, spikeHist and ratePSD
- remaining other funcs such as plotConn

**Comment by joewgraham** [comment]
@salvadord , I'm trying to get NetSims plotted in the new plotRaster, but it doesn't seem like it's working in the original.  

    sim.analysis.plotRaster(include=['allCells'])  # produces the expected results.  
    sim.analysis.plotRaster(include=['all'])  # produces the same plot, but includes 'NetStims' in legend
    sim.analysis.plotRaster(include=['allNetStims'])  # crashes

It seems that the key 'stims' is created in the 'allSimData' dict, but is never filled with anything...  I've been trying to figure out the problem but it's non-trivial.  Help?
