### ISSUE TITLE
Integrate with git/hg 

### ISSUE THREAD

**Issue by salvadord** [suny-downstate-medical-center/netpyne#222]
- commit every time a simulation is executed
- or changes in netParams happen -- update new version
- allow going back to prev sim (commit)

**Comment by pgleeson** [comment]
@salvadord you might want to look at @apdavison's [Sumatra](http://neuralensemble.org/sumatra/) before building anything yourself...

**Comment by salvadord** [comment]
see https://gitlab.com/Solinas/GL_plasticity/blob/dev_ss/Start.py
