### ISSUE TITLE
Targeting group of sections in specific location within connParams

### ISSUE THREAD

**Issue by rodriguez-facundo** [suny-downstate-medical-center/netpyne#285]
Working within connParams, it is possible to specify a target _'loc'_ for the postsynaptic connection, but only if we have a single _'sec'_.

I would like to have the flexibility to specify connections in a detailed way, without having to relax any of the geometric variables _(sec or loc)_ in morphological detailed neurons.

**Comment by salvadord** [comment]
@rodriguez-facundo  Can you please put a specific example of how the connParams rule would look like and the result you would expect please? I know we discussed this, but just to remind me exactly of what you needed. thanks

**Comment by salvadord** [comment]
@rodriguez-facundo - is this still an issue? can you put an example if so?

**Comment by rodriguez-facundo** [comment]
no. now it is possible to do that.
