### ISSUE TITLE
`include: "allCells"`  fails to plot raster

### ISSUE THREAD

**Issue by rodriguez-facundo** [suny-downstate-medical-center/netpyne#395]
`include: "allCells"`    fails to plot raster because the str must be inside a list --> `include: ["allCells"]`

we should correct this to avoid people not being able to plot a raster just because they forgot to wrap the str in a list

what do you think @salvadord

**Comment by salvadord** [comment]
This is explained in the doc, but sure can make it work also without the square brackets. Just need to make sure the changes don't screw up any of the other options.
