### ISSUE TITLE
Simplified cellParams specifications

### ISSUE THREAD

**Issue by salvadord** [suny-downstate-medical-center/netpyne#488]
Proposal: use the cellParams key as 'cellType' when no 'conds' are included:

- This would represent a simplified and more intuitive way of defining cell types

- Only applies if no 'conds' are included, in which case the cellParams key is compared to the popParams 'cellType' 

- Matches more closely the neuroml and sonata specifications

- Backward compatible since can still use the 'conds' method (existing models still work)

- eg. 
```
netParams.popParams['E'] = {'cellType': 'PYR', 'numCells': 20}
netParams.cellParams['PYR'] = {'secs': {'soma': {'mechs': ... , 'geom': ...}}  # no 'conds' defined
```

- Implemented this method in 'simple_cellparams' branch: https://github.com/Neurosim-lab/netpyne/tree/simple_cellparams

- required only a few minor changes in compartCell.py: https://github.com/Neurosim-lab/netpyne/blob/simple_cellparams/netpyne/cell/compartCell.py#L98

- updated HHTut example and tutorials 1-6 to use new simplified method: https://github.com/Neurosim-lab/netpyne/blob/simple_cellparams/doc/source/code/tut2.py

@pgleeson @tarelli @ddelpiano @filippomc @rodriguez-facundo @joewgraham please let me know what you think.

**Comment by joewgraham** [comment]
I think it's a great improvement.  The setup process (and the tutorials) are much more intuitive.
