### ISSUE TITLE
[New feature] Improve import error handling in sonataImport

### ISSUE THREAD

**Issue by joewgraham** [suny-downstate-medical-center/netpyne#494]
This modules imports several Python packages I didn't have installed.  The error message I got wasn't useful.  The message should state exactly why the multiple imports failed. 

https://github.com/Neurosim-lab/netpyne/blob/development/netpyne/conversion/sonataImport.py

**Comment by dhasegan** [comment]
Fix: https://github.com/Neurosim-lab/netpyne/pull/602
