### ISSUE TITLE
[New feature] NetPyNE should try to catch if there are uncompiled mod files that cause an error

### ISSUE THREAD

**Issue by joewgraham** [suny-downstate-medical-center/netpyne#524]
I forget to compile mod files all the time, and often the crash occurs in NEURON and seems unrelated to mod files.

**Comment by jpalma-espinosa** [comment]
Hi!
should it be easier to just compile mod files as the simulation starts? 
or to find for the x86_64 folder that NEURON outputs?

**Comment by jpalma-espinosa** [comment]
@salvadord  would you assign this to me?
I have some ideas that I think should work

**Comment by salvadord** [comment]
sounds good, note this requires several steps: 1) checking if there are mod files in the same folder or in a /mod folder (others?), 2) checking if thsoe mod files are compiled or not, 3) compiling the mod files, 4) loading the mod files into the current session ... even after compiling them they won't be available unless you load them/import the mechanisms (there's a NEURON command for this)

**Comment by salvadord** [comment]
@vvbragin @jchen6727 @urdapile did we end up implementing something for this? there's a package from De Schepper's BSB package that does something similar

**Comment by vvbragin** [comment]
From recently, we have similar functionality when load model from index file. Definitely we can use it for more general case, I'll take a look

**Comment by vvbragin** [comment]
most of suggestions implemented here: https://github.com/suny-downstate-medical-center/netpyne/commit/0becdf621bf42cf4466d8a8987e3d6ef3f59aebd
