### ISSUE TITLE
Enable defining connParams 'synsPerConn' param using string-based functions

### ISSUE THREAD

**Issue by salvadord** [suny-downstate-medical-center/netpyne#537]
e.g. allow a binomial distribution for 'synsPerConn'

**Comment by joewgraham** [comment]
See string-functions for other connectivity params here: http://netpyne.org/reference.html#function-string

**Comment by dhasegan** [comment]
Is this still an issue? I see at http://netpyne.org/reference.html#connectivity-rules
```
synsPerConn (optional) - Number of individual synaptic connections (synapses) per cell-to-cell connection (connection)
Can be defined as a function (see Functions as strings).
```

Also mentioned at:
https://github.com/Neurosim-lab/netpyne/blob/development/netpyne/network/conn.py#L254

**Comment by salvadord** [comment]
No I believe it is already possible to use string-based-functions in 'synsPerConn'. Thanks for pointing this @dhasegan. It would be good to try this with a binomial distribution as requested above, and maybe include it in one of the netpyne tutorials/examples.
