### ISSUE TITLE
plotRaster crashes when including stims

### ISSUE THREAD

**Issue by joewgraham** [suny-downstate-medical-center/netpyne#552]
There was an exception in plotRaster(): 
    "['tags'] not found in axis" 
    (<class 'KeyError'>, KeyError("['tags'] not found in axis"), <traceback object at 0x151cf3c40>)

**Comment by salvadord** [comment]
@urdapile  is this still an issue?

**Comment by vvbragin** [comment]
@salvadord I couldn't reproduce this

**Comment by urdapile** [comment]
@vvbragin @salvadord Sorry the delay. I think I solved in the PR #693, as Adam also pointed out something similar in the NetPyNE channel in Slack at that time. By then, I was working a bit to get the NetStims be included properly in the plotRaster.
