### ISSUE TITLE
Make it possible to record the current from an IClamp

### ISSUE THREAD

**Issue by joewgraham** [suny-downstate-medical-center/netpyne#553]
IClamp in NEURON assigns current to an 'i' variable, so it should be pretty easy to record that
https://github.com/neuronsimulator/nrn/blob/master/src/nrnoc/stim.mod

It seems like the code for this is already in place, but it doesn't seem to work
https://github.com/Neurosim-lab/netpyne/blob/development/netpyne/cell/cell.py#L215

An entry is created in the sim.allSimData dictionary (e.g. 'myIClamp') but it is empty.

**Comment by vvbragin** [comment]
https://github.com/suny-downstate-medical-center/netpyne/commit/0986040b7be38ee9476a92a5917fcbc4e6b3ae5b
