### ISSUE TITLE
Allow string functions for parameter values

### ISSUE THREAD

**Issue by salvadord** [suny-downstate-medical-center/netpyne#58]
- eg. 'gnabar':[0.11, 0.13] and each cell being assigned a random value within that range
- use string functions, same as for conn

**Comment by joewgraham** [comment]
We want to be able to use string-functions to specify parameter values, e.g.:
'gnabar': 'uniform(0.11, 0.13)'
or 
'gnabar': '0.02 * <path_distance_from_soma> + normal(0.12, 0.012)'

**Comment by salvadord** [comment]
@vvbragin @urdapile @jchen6727 - this was implemented for synMechParams but not yet for cellParams, right?

**Comment by vvbragin** [comment]
@salvadord no, it's implemented for cellParams as well (for `geom`, properties of `mechs` and `pointps`)
