### ISSUE TITLE
Issue with batch and mpi4py

### ISSUE THREAD

**Issue by josemendez-villanueva** [suny-downstate-medical-center/netpyne#682]
I am running the batch.py file from netpyne/examples/optunaOptim. When I try testing this file out it does not generate the data json files needed for a job to complete. No error messages show up but the jobs completed always displays 'Completed: 0' and defaults to maxFitness. This issue seems to be due to mpi4py being installed. Once mpi4py is uninstalled the data files are generated but then only one job runs at a time.

This file has been ran with python 3.7/3.8 on both Ubuntu/MacOS.

**Comment by vvbragin** [comment]
Fixed in scope of https://github.com/suny-downstate-medical-center/netpyne/commit/be0815bddd7ced2c65c60b307878ccb5ff8dcb54
