### ISSUE TITLE
Remove matplotlib version requirements after next matplotlib update

### ISSUE THREAD

**Issue by joewgraham** [suny-downstate-medical-center/netpyne#692]
The latest matplotlib release has a bug when trying to copy rcParams (required for new plotting).

I changed the version requirement to <=3.5.1 in both requirements.txt and install_requires in setup.py.

After the next matplotlib release, we should test again and remove version requirement when corrected.

**Comment by sanjayankur31** [comment]
I think it's time to remove this---3.6.x is now out.

**Comment by vvbragin** [comment]
done
