### ISSUE TITLE
netpyne run failure with a neuron 7.7

### ISSUE THREAD

**Issue by dchoi** [suny-downstate-medical-center/netpyne#700]
I am having a difficulty running a netpyne-neuron model (A1 test) with neuron 7.7. neuron 7.7 was installed with intel/19.1.1.217 and intel-mpi/2019.8.254. A simple HH netpyne test is running fine and a neuron-only runs with a neuron model. The problem seems something to do with python link with netpyne at this time. Please let me know what I should try to debug or fix the problem. Here are some information of successfu HH run, neuron-only run and failed netpyne-neuron run.

run-environment
==========================================================
> netpyne is installed on anaconda3 using pip
> module load intel intel-mpi

HH run
==========================================================
>  python HHTut_run.py
...
Warning: no DISPLAY environment variable.
--No graphics will be displayed.

Start time:  2022-07-06 22:02:50.759491

NetParams validation successful ...

Creating network of 1 cell populations on 1 hosts...
  Number of cells on node 0: 200
  Done; cell creation time = 0.02 s.
Making connections...
  Number of connections on node 0: 1623
  Done; cell connection time = 0.16 s.
Adding stims...
  Number of stims on node 0: 200
  Done; cell stims creation time = 0.02 s.
Recording 201 traces of 2 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 4.75 s; real-time ratio: 0.21.

neuron-only run
==========================================================
> mpirun -np 124 ./x86_64/special -mpi -c stop_time=1000 -c is_split=1 parinit.hoc
...
numprocs=124
NEURON -- VERSION 7.7.2 7.7 (2b7985ba) 2019-06-20
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2018
See http://neuron.yale.edu/neuron/credits

Additional mechanisms from files
 ThreshDetect.mod ampanmda.mod fi.mod kamt.mod kdrmt.mod naxn.mod
cxgranule=177
cxspine=19
cxmitral=1234
cxsecden=502
cxmainmitral=232
cxfi=3
cxampa=4
cxtd=1
500 first and last mitral at 5 4995
10000 first and last granule at 0.25 4999.75
o26e500w080w120d001-1s-10pc
stim-o26.hoc
setuptime=11.82
tnext = 1000

netpyne-neuron (7.7.1) run
==========================================================
> mpirun -n 70 ./x86_64/special -python -mpi init.py simConfig=data/v34_batch60/v34_batch60_0_0_cfg.json netParams=data/v34_batch60/v34_batch60_netParams.py
...
numprocs=70
NEURON -- VERSION 7.7.2 7.7 (2b7985ba) 2019-06-20
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2018
See http://neuron.yale.edu/neuron/credits

Additional mechanisms from files
 mod/APCounter2.mod mod/CA1ika.mod mod/CA1ikdr.mod mod/CA1ina.mod mod/Cadynamics.mod mod/DynamicNetStim.mod mod/HH2.mod mod/HH_traub.mod mod/IC.mod mod/ICal.mod mod/IKM.mod mod/IKsin.mod mod/IL.mod mod/IL_gutnick.mod mod/IM_cortex.mod mod/IT.mod mod/IT2.mod mod/Iahp.mod mod/Ican.mod mod/MyExp2SynAlpha.mod mod/MyExp2SynBB.mod mod/MyExp2SynNMDABB.mod mod/Nca.mod mod/ar_traub.mod mod/beforestep_py.mod mod/cad.mod mod/cadad.mod mod/cadecay_destexhe.mod mod/cadyn.mod mod/cagk.mod mod/cal_mh.mod mod/cal_mig.mod mod/can_mig.mod mod/cancr.mod mod/canin.mod mod/caolmw.mod mod/capr.mod mod/cat_mig.mod mod/cat_traub.mod mod/catcb.mod mod/ch_CavL.mod mod/ch_CavN.mod mod/ch_KCaS.mod mod/ch_Kdrfastngf.mod mod/ch_KvAngf.mod mod/ch_KvCaB.mod mod/ch_Navngf.mod mod/ch_leak.mod mod/cp.mod mod/cp2.mod mod/gabab.mod mod/h_BS.mod mod/h_harnett.mod mod/h_kole.mod mod/h_migliore.mod mod/hin.mod mod/htc.mod mod/ican_sidi.mod mod/icaolmw.mod mod/icapr.mod mod/iccr.mod mod/iconc_Ca.mod mod/iholmkop.mod mod/iholmw.mod mod/ihpyrkop.mod mod/ikscr.mod mod/ipulse3.mod mod/kBK.mod mod/kahppr.mod mod/kaolmkop.mod mod/kap_BS.mod mod/kapcb.mod mod/kapin.mod mod/kapyrkop.mod mod/kca.mod mod/kcaolmw.mod mod/kcpr.mod mod/kctin.mod mod/kdmc_BS.mod mod/kdr2_orig.mod mod/kdr_BS.mod mod/kdrbwb.mod mod/kdrcr.mod mod/kdrin.mod mod/kdrolmkop.mod mod/kdrpr.mod mod/kdrpyrkop.mod mod/kl.mod mod/km.mod mod/kv.mod mod/my_exp2syn.mod mod/na_2.mod mod/naf2.mod mod/nafbwb.mod mod/nafcr.mod mod/nafolmkop.mod mod/nafpr.mod mod/nafpyrkop.mod mod/nafx.mod mod/nap_sidi.mod mod/nax_BS.mod mod/naz.mod mod/ntIh.mod mod/ntleak.mod mod/ntt.mod mod/ntt_int.mod mod/pasi.mod mod/savedist.mod mod/tia.mod mod/vecstim.mod mod/wrap.mod
8 /home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: can't open -python
Abort(-1) on node 8 (rank 8 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 8
31 /home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: can't open -python
Abort(-1) on node 31 (rank 31 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 31
42 /home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: can't open -python
Abort(-1) on node 42 (rank 42 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 42

**Comment by salvadord** [comment]
@dchoi can you try `mpirun -n 2 ./x86_64/special -mpi -python HHTut_run.py` ?

**Comment by dchoi** [comment]
I got the similar error:
 
  mpirun -n 2 ./x86_64/special -mpi -python HHTut_run.py
/home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: /lib64/libtinfo.so.6: no version information available (required by /home/dchoi/apps/nrn-7.7-impi/x86_64/lib/libmemacs.so.0)
/home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: /lib64/libtinfo.so.6: no version information available (required by /home/dchoi/apps/nrn-7.7-impi/x86_64/lib/libreadline.so.0)
/home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: /lib64/libtinfo.so.6: no version information available (required by /home/dchoi/apps/nrn-7.7-impi/x86_64/lib/libmemacs.so.0)
/home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: /lib64/libtinfo.so.6: no version information available (required by /home/dchoi/apps/nrn-7.7-impi/x86_64/lib/libreadline.so.0)
numprocs=2
NEURON -- VERSION 7.7.2 7.7 (2b7985ba) 2019-06-20
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2018
See http://neuron.yale.edu/neuron/credits

Additional mechanisms from files

0 /home/dchoi/apps/nrn-7.7-impi/x86_64/bin/nrniv: can't open -python
Abort(-1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
(ba

**Comment by salvadord** [comment]
outdated, reopen if still an issue
