### ISSUE TITLE
Add documentation for the complex stimulation (extend connParams, stimSourceParams, stimTargetParams)

### ISSUE THREAD

**Issue by ddelpiano** [suny-downstate-medical-center/netpyne#734]
As discussed at the sprint meeting, currently the documentation for the complex stimulation is missing.

**Comment by ddelpiano** [comment]
https://github.com/OpenSourceBrain/OSBv2/blob/master/docs/osb-applications-protocol.md

**Comment by salvadord** [comment]
examples in this repo: https://github.com/jonescompneurolab/hnn/tree/hnn2

**Comment by vvbragin** [comment]
https://app.asana.com/0/1200408935614168/1203972875087861/f

**Comment by jchen6727** [comment]
https://github.com/suny-downstate-medical-center/netpyne/pull/743

documentation to reference.rst and within the relevant python files.
