### ISSUE TITLE
NetPyNE and fMRI/DTI data

### ISSUE THREAD

**Issue by LuRoe7** [suny-downstate-medical-center/netpyne#759]
I have functional and structural connectivity matrices from patients with schizophrenia and healthy controls based on resting-state fMRI and DTI, respectively. These matrices reflect the connectivity between certain brain regions/neural populations. Now, I'd like to develop several biophysical brain networks to find the one which explains the observed connectivity patterns in patients and controls most accurately. The overall aim is to provide insight into the potential underlying alterations within certain brain network in schizophrenia that may drive  the observable alterations in connectivity as measured by rs-fMRI and DTI.

Now, two questions:

1. (How) Can NetPyNE be used to achieve that?
2. Does anyone have an example in which NetPyNE was in combination with fMRI or DTI data?

Thanks in advance!
Best,
Lukas

**Comment by vvbragin** [comment]
Dear Lukas,

In principle, NetPyNE as a standalone tool is applicable for such task (although we are not aware of any existing examples): you can develop biophysical models for certain regions of interest, and assemble them into a bigger network by interconnecting them using connectivity strength (probability or/and weight of connections) and time delays based on functional and structural connectivity matrices you have.

However, if your connectivity matrices' coverage is broad enough, you might be interested in large-scale model using the interface between NetPyNE and [TheVirtualBrain](https://www.thevirtualbrain.org/tvb/zwei). In a nutshell, TVB is a software for simulating large-scale networks comprised of nodes (brain regions) represented by mean-field models, and interconnected with weights and delays inferred from fMRI and DTI data. Further, there is an extension called [TVB-Multiscale](https://www.youtube.com/watch?v=6hEuvxD7IDk), which allows for 'replacing' a subset of mean-filed regions with detailed spiking networks. Such interface for NetPyNE is recently developed and being actively flight tested, [here](https://github.com/vvbragin/CNS2023-TVB-NetPyNE) you can find some more info and references from its presentation at CNS*2023.

Hope this can help, and feel free to get in touch with any questions! @LuRoe7

Best regards,
Valery
