### ISSUE TITLE
[other] Dependency on future

### ISSUE THREAD

**Issue by frenzymadness** [suny-downstate-medical-center/netpyne#773]
Hello. I see that the project depends on future for Python 2 compatibility. Do you think it's still useful? I'm asking because future is broken with the latest Python 3.12 and will be even more with 3.13 so it might be a good idea to get rid of it.

**Comment by sanjayankur31** [comment]
@salvadord : this should hopefully be a simple one, but it's a critical update required to ensure that netpyne continues to work with py3.13. Any chance it could be moved up in the priority list please?

This already affects Fedora "rawhide" which will become Fedora 41, where py3.13 is going to soon be default.

https://bugzilla.redhat.com/show_bug.cgi?id=2276614

**Comment by vvbragin** [comment]
hi @sanjayankur31 got iit, I'll check today and let you know

**Comment by vvbragin** [comment]
hi @sanjayankur31, this is done: https://github.com/suny-downstate-medical-center/netpyne/commit/ff8bb97b2fa88ba59333057d151abbb6d7d2d821
Will be included into upcoming release

**Comment by sanjayankur31** [comment]
Awesome, thanks :+1:

**Comment by frenzymadness** [comment]
The usages of the future have been removed from the code but the dependency is still specified in the metadata. Could this issue be reopened?

In requirements:

https://github.com/suny-downstate-medical-center/netpyne/blob/a0846bbeeac6f81be4981035463ef5b420459071/requirements.txt#L5

in setup.py:

https://github.com/suny-downstate-medical-center/netpyne/blob/a0846bbeeac6f81be4981035463ef5b420459071/setup.py#L78
