### ISSUE TITLE
[other] load_file return value is not considered

### ISSUE THREAD

**Issue by aranega** [suny-downstate-medical-center/netpyne#782]
Currently, the [`importCellParams` method](https://github.com/suny-downstate-medical-center/netpyne/blob/7ba27ac0d6bfb3616021d6b1a2ecddd31dc42a7e/netpyne/specs/netParams.py#L633C9-L633C25) uses the `importCell` function which loads `.hoc` file using the [`load_file` function](https://github.com/suny-downstate-medical-center/netpyne/blob/7ba27ac0d6bfb3616021d6b1a2ecddd31dc42a7e/netpyne/conversion/neuronPyHoc.py#L289C14-L289C14) from NEURON. The `load_file` function returns `0` when an error occured (file not found, or an interpreter error while loading the file), but doesn't trigger any exception. In case the `load_file` fails, there is no way of knowing that an error happened. It would be interesting to get the error code and to raise a dedicated exception in case the function fails. That would let nepyne users the possibility to implement their own error handling :)

**Comment by vvbragin** [comment]
Hi @aranega thanks for noting this. For now we don't have any netpyne-specific expection types, so I'm just throwing a default exception if load_file return zero code: https://github.com/suny-downstate-medical-center/netpyne/commit/a7c06ec8f760d8ea136ef950d2d66e1f024df394
