### ISSUE TITLE
Batch experiment reacts strangely when 0 is used for population number of cell

### ISSUE THREAD

**Issue by aranega** [suny-downstate-medical-center/netpyne#793]
**Bug description**

When working on NetPyNE-UI, we observed that when we create an experiment with value for the `netParams.popParams.XXX.numCells` going from `0` to any value, the result for the `0` value of the parameter actually includes the original number of cell of the model instead of `0` even if `0` is well written in the experiment files.

**Reproducing the bug**

Attached to this issue, you can [find a zip]((https://github.com/suny-downstate-medical-center/netpyne/files/13279570/myExperiment.zip) with the code related to the experiment and the different model produced.
You can see that the `myExperiment_batch.json` file contains those parameters for the simulations:

```json
"params": [
            {
                "label": "popParams.E.numCells",
                "values": [
                    0,
                    1
                ]
            }
        ],
```
While the model `myExperiment_0_data.json` contains:

```json
"popParams": {
                "E": {
                    "cellType": "pyr",
                    "numCells": 40,
                    "pop": "E"
                }
            },
```
with the model fully serialized, but not for `myExperiment_1_data.json` that properly has only 1 cell as population.

**Expected behavior**

**System information**

- OS and version: Linux (archlinux) kernel 6.5.9
 - NetPyNE version: version from `develop`, commit cdb1697294085256805fc9eeb2a14a08fb342d6d
 - NEURON version: 8.2.2
 - Python version: 3.7.12

**Attached files**

[myExperiment.zip](https://github.com/suny-downstate-medical-center/netpyne/files/13279570/myExperiment.zip)

**Comment by jchen6727** [comment]
Hi, the current NetPyNE code doesn't traverse the cfg dictionary in this way, see: 
```
    def setCfgNestedParam(self, paramLabel, paramVal):
        if isinstance(paramLabel, tuple):
            container = self.cfg
            for ip in range(len(paramLabel) - 1):
                if isinstance(container, specs.SimConfig):
                    container = getattr(container, paramLabel[ip])
                else:
                    container = container[paramLabel[ip]]
            container[paramLabel[-1]] = paramVal
        else:
            setattr(self.cfg, paramLabel, paramVal)  # set simConfig params
``` 
although I agree that using '.' delimiter would be more straightforward.

**Comment by jchen6727** [comment]
oh, I'm sorry, hadn't looked at the right piece of code:

```
    def setCfgMapping(self, cfg):
        if hasattr(self, 'mapping'):
            for k, v in self.mapping.items():
                if getattr(cfg, k, None):
                    self.setNestedParam(v, getattr(cfg, k))
```

`if 0:` :/

**Comment by jchen6727** [comment]
can close if passing test cases now
