### ISSUE TITLE
[other] netpyne.org: "Read the docs" link in the middle returns to page -> linked back to netpyne.org

### ISSUE THREAD

**Issue by sanjayankur31** [suny-downstate-medical-center/netpyne#799]
**Please describe your issue**

Sorry, wasn't sure where to file this. The big button in the middle of netpyne.org that says "Read the docs" links back to "netpyne.org". It should probably link to doc.netpyne.org?

**Comment by Myrausman** [comment]
@sanjayankur31 
Hi, I'm not sure if this issue is addressed, but it seems to be working as you expected.

**Comment by sanjayankur31** [comment]
Yep, I'll close this now.
